name: Deploy on GitHub Pages

on:
  push:
    branches:
      - master  # Измените это на основную ветку вашего репозитория

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code of the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Webpack serve
        run: npm run build

      - name: Deploying to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Deploying on the GitHub Pages"
          git push -u origin main:gh-pages  # Пушим в ветку gh-pages
